[logger]
level = "INFO"
output = "stdout"

[endpoint]
host = ""
httpPort = 8080
grpcPort = 15000

[storage]
mode = "postgres"
# mode = "postgres"  # memory, postgres
host = "localhost"
port = 5432
dbname = "calendar_db"
user = "otus"
password = "password"
