[logger]
level = "INFO"
output = "stdout"

[http]
host = ""
port = 8080

[storage]
mode = "memory"
# mode = "postgres"  # memory, postgres
# host = "localhost"
# port = 5432
# dbname = "calendar_db"
# user = "otus"
# password = "password"
