services:
  postgresql:
    image: postgres:16.1-alpine3.19
    environment:
      - POSTGRES_USER=otus
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=calendar_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      calendar-network:
        aliases:
          - postgresql

networks:
  calendar-network:

volumes:
  pgdata: